/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconCalendar: typeof import('@element-plus/icons-vue')['Calendar']
    ElIconCirclePlus: typeof import('@element-plus/icons-vue')['CirclePlus']
    ElIconDataLine: typeof import('@element-plus/icons-vue')['DataLine']
    ElIconDocumentChecked: typeof import('@element-plus/icons-vue')['DocumentChecked']
    ElIconKey: typeof import('@element-plus/icons-vue')['Key']
    ElIconMap: typeof import('@element-plus/icons-vue')['Map']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconStarFilled: typeof import('@element-plus/icons-vue')['StarFilled']
    ElIconUserSolid: typeof import('@element-plus/icons-vue')['UserSolid']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
